
## Name: Simran Anand



### 1.	Assuming a set of documents that need to be classified, use the naïve Bayesian Classifier model to perform this task. 

In [ ]:
import pandas as pd
msg=pd.read_csv('C:/Users/simran/Downloads/naivetext.csv',names=['message','label'])
print('The dimensions of the dataset',msg.shape)
msg['labelnum']=msg.label.map({'pos':1,'neg':0})
X=msg.message
y=msg.labelnum
print(X)
print(y)

The dimensions of the dataset (18, 2)
0                      I love this sandwich
1                  This is an amazing place
2        I feel very good about these beers
3                      This is my best work
4                      What an awesome view
5             I do not like this restaurant
6                  I am tired of this stuff
7                    I can't deal with this
8                      He is my sworn enemy
9                       My boss is horrible
10                 This is an awesome place
11    I do not like the taste of this juice
12                          I love to dance
13        I am sick and tired of this place
14                     What a great holiday
15           That is a bad locality to stay
16           We will have good fun tomorrow
17         I went to my enemy's house today
Name: message, dtype: object
0     1
1     1
2     1
3     1
4     1
5     0
6     0
7     0
8     0
9     0
10    1
11    0
12    1
13    0
14    1
15    0
16    1
17   

In [ ]:
#splitting the dataset into train and test data
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y)
print ('\n The total number of Training Data :',ytrain.shape)
print ('\n The total number of Test Data :',ytest.shape)




 The total number of Training Data : (13,)

 The total number of Test Data : (5,)


In [ ]:
#output of count vectoriser is a sparse matrix
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
xtrain_dtm = count_vect.fit_transform(xtrain)
xtest_dtm=count_vect.transform(xtest)
print('\n The words or Tokens in the text documents \n')
print(count_vect.get_feature_names())
df=pd.DataFrame(xtrain_dtm.toarray(),columns=count_vect.get_feature_names())



 The words or Tokens in the text documents 

['am', 'amazing', 'an', 'and', 'awesome', 'bad', 'best', 'boss', 'can', 'dance', 'deal', 'do', 'enemy', 'fun', 'good', 'have', 'he', 'horrible', 'house', 'is', 'like', 'locality', 'love', 'my', 'not', 'of', 'place', 'restaurant', 'sick', 'stay', 'stuff', 'sworn', 'that', 'this', 'tired', 'to', 'today', 'tomorrow', 'we', 'went', 'will', 'with', 'work']


In [ ]:
# Training Naive Bayes (NB) classifier on training data.
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(xtrain_dtm,ytrain)
predicted = clf.predict(xtest_dtm)



In [ ]:
#printing accuracy, Confusion matrix, Precision and Recall
from sklearn import metrics
print('Accuracy metrics')
print('Accuracy of the classifer is',metrics.accuracy_score(ytest,predicted))
print('Confusion matrix')
print(metrics.confusion_matrix(ytest,predicted))
print('Recall and Precison ')
print(metrics.recall_score(ytest,predicted))
print(metrics.precision_score(ytest,predicted))

Accuracy metrics
Accuracy of the classifer is 0.8
Confusion matrix
[[1 0]
 [1 3]]
Recall and Precison 
0.75
1.0


### 2.	Build an Artificial Neural Network by implementing the Backpropagation algorithm and test the same using appropriate data sets. K-NN and Weighted- KNN classifiers

#### Initializing variables value

In [1]:
import numpy as np

x = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)

print("small x",x)

#original output 

y = np.array(([92], [86], [89]), dtype=float)

X = x/np.amax(x,axis=0) #maximum along the first axis 

print("Capital X",X)

small x [[2. 9.]
 [1. 5.]
 [3. 6.]]
Capital X [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]


In [2]:
#Defining Sigmoid Function for output 

def sigmoid (x):

    return (1/(1 + np.exp(-x)))

#Derivative of Sigmoid Function

def derivatives_sigmoid(x):

    return x * (1 - x)

#Variables initialization

epoch=7000 #Setting training iterations

lr=0.1 #Setting learning rate

inputlayer_neurons = 2 #number of input layer neurons 

hiddenlayer_neurons = 3 #number of hidden layers neurons

output_neurons = 1 #number of neurons at output layer

Note:

1)In this code,we have defined  sigmoid function and its derivative function.

2)As you know, we train the Neural network many times at a single point, for that we need the number of epochs.

3)Below that we have defined the only  number of neurons in each layer.

In [3]:
#Defining weight and biases for hidden and output layer 

wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))

bh=np.random.uniform(size=(1,hiddenlayer_neurons))

wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))

bout=np.random.uniform(size=(1,output_neurons))

Note: 

1.Here we have defined random weights and bias

2.As we know, we should first defined the weights and Bias for the first (here we have only one hidden layer) hidden layer.

3.After that we have defined the weights and bias for the output layer.

4.Keep in mind when defining the weights size (how many neurons are in the previous layer, the number of neurons in the layer for that we have defined weights).

5.Size of bias (number of neurons in output layer,the number of neurons in the layer for that we have defined biases).

In [4]:
#Forward Propagation 

for i in range(epoch):

    hinp1=np.dot(X,wh) 

    hinp=hinp1 + bh

    hlayer_act = sigmoid(hinp)

    outinp1=np.dot(hlayer_act,wout)

    outinp= outinp1+ bout

    output = sigmoid(outinp)

Note:

1.Here we are just calculating output of our model, first we have done this for hidden layer and after that for output layer , and finally get the output.

2.np.dot is used for dot product of two matrix.

In [5]:
#Backpropagation Algorithm 

EO = y-output

outgrad = derivatives_sigmoid(output)

d_output = EO* outgrad

EH = d_output.dot(wout.T)

hiddengrad = derivatives_sigmoid(hlayer_act)

#how much hidden layer wts contributed to error

d_hiddenlayer = EH * hiddengrad

wout += hlayer_act.T.dot(d_output) *lr

# dotproduct of nextlayererror and currentlayerop

bout += np.sum(d_output, axis=0,keepdims=True) *lr

#Updating Weights

wh += X.T.dot(d_hiddenlayer) *lr

print("Actual Output: \n" + str(y))

print("Predicted Output: \n" ,output)

Actual Output: 
[[92.]
 [86.]
 [89.]]
Predicted Output: 
 [[0.71291985]
 [0.7074581 ]
 [0.71405303]]


Note: 

1.In this code first we calculated error of hidden layer and after that calculated error of output layer.

2.As we know from the formula we have to find out  how much hidden layer contribute in total error and also contribution of weight in total error.

3.After that we have updated our weights and biases, until we get minimum error.

4.X.T is used to make transpose matrix.